const productosRaw = 

[
  {
    id: 1,
    codigo: "COC-600-PET",
    categoria: "BEBIDAS",
    nombre: "COCA COLA ORIGINAL",
    marca: "COCA COLA",
    modelo: "CLASSIC",
    presentacion: "BOTELLA PET 1.5L",
    proveedor_nombre: "COCA COLA ANDINA",
    proveedor_condicion_fiscal: "Responsable Inscripto",
    precio_unitario_neto: 1200.00,
    iva_incluido: false,
    alicuota_detectada: 21.0,
    precio_final: 1452.00
  },
  {
    id: 2,
    codigo: "CER-001-PAT",
    categoria: "BEBIDAS",
    nombre: "CERVEZA PATAGONIA AMBER",
    marca: "PATAGONIA",
    modelo: "AMBER LAGUERN",
    presentacion: "LATA 473ML",
    proveedor_nombre: "CERVECERIA QUILMES",
    proveedor_condicion_fiscal: "Responsable Inscripto",
    precio_unitario_neto: 850.50,
    iva_incluido: false,
    alicuota_detectada: 21.0,
    precio_final: 1029.11
  },
  {
    id: 3,
    codigo: "AGU-500-VIV",
    categoria: "BEBIDAS",
    nombre: "AGUA MINERAL VILLAVICENCIO",
    marca: "VILLAVICENCIO",
    modelo: "SIN GAS",
    presentacion: "BOTELLA 500ML",
    proveedor_nombre: "DISTRIBUIDORA DEL SUR",
    proveedor_condicion_fiscal: "Responsable Inscripto",
    precio_unitario_neto: "_",
    iva_incluido: true,
    alicuota_detectada: 21.0,
    precio_final: 450.00
  },{
    id: 4,
    codigo: "AGU-500-VIV",
    categoria: "BEBIDAS",
    nombre: "AGUA MINERAL VILLAVICENCIO",
    marca: "VILLAVICENCIO",
    modelo: "SIN GAS",
    presentacion: "BOTELLA 500ML",
    proveedor_nombre: "DISTRIBUIDORA DEL SUR",
    proveedor_condicion_fiscal: "Responsable Inscripto",
    precio_unitario_neto: "_",
    iva_incluido: true,
    alicuota_detectada: 21.0,
    precio_final: 450.00
  },
  {
    id: 5,
    codigo: "ALM-050-ART",
    categoria: "ALIMENTOS",
    nombre: "ALFAJOR ARTESANAL DE MAICENA",
    marca: "DULCES DEL VALLE",
    modelo: "TRADICIONAL",
    presentacion: "UNIDAD 50G",
    proveedor_nombre: "JUAN PEREZ REPOSTERIA",
    proveedor_condicion_fiscal: "Monotributista",
    precio_unitario_neto: "_",
    iva_incluido: false,
    alicuota_detectada: 0.0,
    precio_final: 350.00
  },
  {
    id: 6,
    codigo: "PAN-001-CAS",
    categoria: "PANADERIA",
    nombre: "PAN INTEGRAL SEMILLADO",
    marca: "EL HORNO DE ANA",
    modelo: "INTEGRAL",
    presentacion: "BOLSA 400G",
    proveedor_nombre: "ANA GARCIA",
    proveedor_condicion_fiscal: "Monotributista",
    precio_unitario_neto: "_",
    iva_incluido: false,
    alicuota_detectada: 0.0,
    precio_final: 900.00
  },
]

export default productosRaw